module.exports = {
  // DRAWER ACTIONS
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',

  // IMAGE
  ACTION_FETCH_IMAGES: 'FETCH_IMAGES',

  // API
  BASE_URL: 'https://chuck-nodejs-exercise1.herokuapp.com/api/contacts',

  // NAVIGATION ACTIONS
  ACTION_SET_PARENT_PAGE: 'SET_PARENT_PAGE',

  // USER ACTIONS
  ACTION_DID_BEGIN_FETCHING: 'DID_BEGIN_FETCHING',
  ACTION_FETCH_USERS_FULLFILLED: 'FETCH_USERS_FULLFILLED',
  ACTION_FETCH_USERS_REJECTED: 'FETCH_USERS_REJECTED',
  ACTION_API_SUCCESS: 'API_SUCCESS',
  ACTION_ADD_USER_REJECTED: 'ADD_USER_REJECTED',
  ACTION_UPDATE_USER_REJECTED: 'UPDATE_USER_REJECTED',
  ACTION_RESET_MESSAGE: 'RESET_MESSAGE',

  // DETAIL ACTIONS
  ACTION_SET_FIRST_NAME: 'SET_FIRST_NAME',
  ACTION_SET_LAST_NAME: 'SET_LAST_NAME',
  ACTION_SET_ADDRESS: 'SET_ADDRESS',
  ACTION_SET_EMAIL: 'SET_EMAIL',
  ACTION_SET_CONTACT_NUMBER: 'SET_CONTACT_NUMBER',
  ACTION_SET_ALL: 'SET_ALL',
  ACTION_RESET: 'RESET',
  ACTION_SET_ID: 'SET_ID',

  // LOGIN
  ACTION_SET_LOGIN_EMAIL: 'SET_LOGIN_EMAIL',
  ACTION_SET_LOGIN_PASSWORD: 'SET_LOGIN_PASSWORD',
  ACTION_SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  ACTION_SET_LOGIN_USERDATA: 'SET_LOGIN_USERDATA',

  // SIGNUP
  ACTION_SET_SIGNUP_EMAIL: 'SET_SIGNUP_EMAIL',
  ACTION_SET_SIGNUP_PASSWORD: 'SET_SIGNUP_PASSWORD',
  ACTION_SET_SIGNUP_ERROR: 'SET_SIGNUP_ERROR',
  ACTION_SET_SIGNUP_SUCCESS: 'SET_SIGNUP_SUCCESS',

  // MESSAGES
  MESSAGE_API_SUCCESS: 'Success!',

  // ICONS
  ICON_MENU: 'ios-menu',
  ICON_BACK: 'ios-arrow-back',
  ICON_ADD: 'ios-add',

  // HEADER TITLES
  HEADER_CAMERA: 'My Camera',
  HEADER_STORAGE: 'My Storage',
  HEADER_CONTACT: 'My Contact',
};
